#!/bin/bash

# Copyright (C) 2016 Michel Müller

# This file is part of Guetzli.

# Guetzli is free software: you can redistribute it and/or modify
# it under the terms of the GNU Lesser General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# Guetzli is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU Lesser General Public License for more details.

# You should have received a copy of the GNU Lesser General Public License
# along with Guetzli. If not, see <http://www.gnu.org/licenses/>.

# ============ preamble ================== #
set -o errexit #exit when command fails
set -o nounset #exit when trying to use undeclared variable
set -o pipefail #pass along errors within a pipe

# =============== setup ================== #
working_dir=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )
log_file="${working_dir}/guetzli_log"
pid_file="${working_dir}/uwsgi.pid"
port=5000
site=""
if [[ $# > 0 ]] ; then
	site="$1"
fi
autopull_key=""
if [[ $# > 1 ]] ; then
	autopull_key="$2"
fi
autopull_branch=""
if [[ $# > 2 ]] ; then
	autopull_branch="$3"
fi
autopull_untrusted=""
if [[ $# > 3 ]] ; then
	autopull_untrusted="$4"
fi

# ========= eat the guetzli ============== #
touch "$log_file"
uwsgi --stop "$pid_file" && :
sleep 1
uwsgi --master --processes 4 --offload-threads 4 --http :$port --daemonize "$log_file" --pidfile "$pid_file" -w server:app --static-map /static="$working_dir/design/static" --pyargv "$site $autopull_key $autopull_branch $autopull_untrusted" --buffer-size 65536 --socket-timeout 5 --listen 5